import mongoose from 'mongoose';

const invoiceSchema = new mongoose.Schema(
  {
    invoiceNumber: {
      type: String,
      unique: true,
      required: false, // Will be generated by pre-save hook or controller
    },
    quoteId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Quote',
      index: true,
    },
    dealId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Deal',
      index: true,
    },
    contactId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Contact',
      required: true,
      index: true,
    },
    companyId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Company',
      index: true,
    },
    status: {
      type: String,
      enum: ['Draft', 'Sent', 'Paid', 'Overdue', 'Cancelled'],
      default: 'Draft',
      index: true,
    },
    lineItems: [
      {
        productId: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'Product',
        },
        description: String,
        quantity: Number,
        unitPrice: Number,
        discount: { type: Number, default: 0 },
        tax: { type: Number, default: 0 },
      },
    ],
    subtotal: {
      type: Number,
      default: 0,
    },
    tax: {
      type: Number,
      default: 0,
    },
    total: {
      type: Number,
      default: 0,
    },
    amountPaid: {
      type: Number,
      default: 0,
    },
    dueDate: Date,
    paidDate: Date,
    notes: String,
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Tenant',
      index: true,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
  },
  {
    timestamps: true,
  }
);

invoiceSchema.index({ invoiceNumber: 1 });
invoiceSchema.index({ status: 1, dueDate: 1 });
invoiceSchema.index({ contactId: 1, companyId: 1 });

// Calculate totals before saving
invoiceSchema.pre('save', function (next) {
  if (this.lineItems && this.lineItems.length > 0) {
    let subtotal = 0;

    this.lineItems.forEach((item) => {
      const quantity = item.quantity || 0;
      const unitPrice = item.unitPrice || 0;
      const discount = item.discount || 0;
      const lineTotal = quantity * unitPrice * (1 - discount / 100);
      subtotal += lineTotal;
    });

    const tax = this.lineItems.reduce((sum, item) => sum + (item.tax || 0), 0);
    this.subtotal = subtotal;
    this.tax = tax;
    this.total = subtotal + tax;
  } else {
    this.subtotal = 0;
    this.tax = 0;
    this.total = 0;
  }
  next();
});

// Generate invoice number before saving
invoiceSchema.pre('save', async function (next) {
  if (!this.invoiceNumber) {
    try {
      // Use a more reliable method to generate unique invoice numbers
      let invoiceNumber;
      let isUnique = false;
      let attempts = 0;
      const maxAttempts = 10;

      while (!isUnique && attempts < maxAttempts) {
        const count = await mongoose.model('Invoice').countDocuments();
        invoiceNumber = `INV-${String(count + 1).padStart(6, '0')}`;
        
        // Check if this invoice number already exists
        const existing = await mongoose.model('Invoice').findOne({ invoiceNumber });
        if (!existing) {
          isUnique = true;
        } else {
          attempts++;
          // Add a small delay to avoid race conditions
          await new Promise(resolve => setTimeout(resolve, 10));
        }
      }

      if (!isUnique) {
        // Fallback: use timestamp-based invoice number
        const timestamp = Date.now();
        invoiceNumber = `INV-${timestamp.toString().slice(-8)}`;
      }

      this.invoiceNumber = invoiceNumber;
    } catch (error) {
      console.error('Error generating invoice number:', error);
      // Fallback invoice number
      this.invoiceNumber = `INV-${Date.now().toString().slice(-8)}`;
    }
  }
  next();
});

export default mongoose.model('Invoice', invoiceSchema);

